# Page settings

#baseURL = "https://cv.okidog.xyz/"
baseURL = "https://heifetzwu.github.io/"
#baseURL = "http://172.18.0.3/"
languageCode = "zh"
title = ""
theme = "hugo-devresume-theme"
googleAnalytics = "UA-XXXXXXX-Y"


[params]
    author = "Jack Wu"
    description = "履歷表"
    primaryColor = "#54B689"
    textPrimaryColor = "#292929"

    [params.profile]
        enable = true
        name = "Jack Wu"
        tagline = "Architect / SRE"
        avatar = "jack1.jpg"

    [params.contact]
        enable = true
        location = "台北"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:#"
        text = "0921xxxxxx"
        id = "tel"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:#"
        text = "heifetzwu@gmail.com"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "#"
        text = "heifetzwu.github.io"


    [params.skills]
        enable = true

        
        
        [[params.skills.list]]
        title = "Database"
        [[params.skills.list.items]]
        details = "Oracle/DB2/MongoDB/mysql/postgreql"
        [[params.skills.list]]
        title = "Scripting"
        [[params.skills.list.items]]
        details = "bash"
        [[params.skills.list]]
        title = "Language"
        [[params.skills.list.items]]
        details = "go"
        [[params.skills.list]]
        title = "Version Control"
        [[params.skills.list.items]]
        details = "git,svn"

        [[params.skills.list]]
        title = "Middleware"
        [[params.skills.list.items]]
        details = "nginx, IBM Websphere"
        [[params.skills.list]]
        title = "CI/CD Tools"
        [[params.skills.list.items]]
        details = "Jenkins"
        [[params.skills.list]]
        title = "Container Orchestration"
        [[params.skills.list.items]]
        details = "Kubernetes, Docker"
        [[params.skills.list]]
        title = "Monitoring"
        [[params.skills.list.items]]
        details = "Prometheus, EFK"
        
        [[params.skills.list]]
        title = "Cloud"
        [[params.skills.list.items]]
        details = "Aws"
        [[params.skills.list]]
        title = "Serveless"
        [[params.skills.list.items]]
        details = "Lambda"
        
        [[params.skills.list]]
        title = "Service Mesh"
        [[params.skills.list.items]]
        details = "Istio"
        [[params.skills.list]]
        title = "Profession"
        [[params.skills.list.items]]
        details = "溝通/團隊合作/問題解決/專案管理"
        [[params.skills.list.items]]
        details = "Design and implement database structures"
        [[params.skills.list.items]]
        details = "Lead and deliver complex software systems"




    [params.education]
        enable = true

        [[params.education.list]]
        degree = "管理科學系"
        university = "國立交通大學"
        dates = "1990 - 1994"
        [[params.education.list]]
        degree = "普通高中"
        university = "師大附中"
        dates = ""








    [params.awards]
        enable = true

	[[params.awards.list]]
        name = "CKA"
        url = "https://www.credly.com/badges/636bfa4b-7f56-49f9-ae2b-92991e998e5c/public_url"
        body = "Certified Kubernetes Architect"
        #body = "https://www.credly.com/badges/636bfa4b-7f56-49f9-ae2b-92991e998e5c/public_url"
        date = "2023/2/15 ~ 2026/2/15"
        

        [[params.awards.list]]
        name = "SAA"
        url = ""
        body = "AWS Certified Solutions Architect - Associate"
        date = "2017/10/26 ~ 2020/10/26"
        
        [[params.awards.list]]
        name = "TOEIC"
        url = ""
        body = "TOEIC Listening and Reading Total Score: 790"
        date = "2016/9/25"
        
        [[params.awards.list]]
        name = "IBM DB2"
        url = ""
        body = "IBM Certified Database Associate -- DB2 Universal Database V8.1 Family"
        date = "2005"
        
        [[params.awards.list]]
        name = "OCP AD"
        url = ""
        body = "Oracle Certified Application Developer Rel.1"
        date = "1999"








    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "中文/台語"
        level = "母語"
        [[params.languages.list]]
        name = "英文"
        level = "流利"




    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "爬山/馬拉松/單車/游泳/瑜珈"
        [[params.interests.list]]
        name = "攝影"
        [[params.interests.list]]
        name = "古典音樂"
        







    [params.summary]
        enable = true
        text = "個性穩定, 負責, 擅長溝通合作, 過往經歷了系統分析以及專案架構師培養了豐富的領導團隊經驗以及扎實的技術基礎。 \n後來因為長輩照護需求, 暫時中斷了工作。\n近年來自我精進雲端, 以及叢集分散式架構, 期許能有更有效率的方式來完成更有價值的工作。"
        
    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "IT顧問"
        dates = "2000 - 2013"
        company = "IBM"
        details = "擔任專案系統架構技術主管/協助專案規畫書建議"
        
        [[params.experience.list.items]]
        #details = "Architect: Design architecture, implement solution that meet FRs, NFRs and interfaces requirements b/w client existing system and new system"
        details = "架構師: 依據專案需求設計架構, 考量專案功能性與非功能性的需求, 佐以調查訪談客戶既有系統的功能與介面據以設計開發新系統"
        [[params.experience.list.items]]
        #details = "DBA: I performed job role of DBA. The job includes database management, migration(Migrate from Oracle to IBM DB2), data synchronization"
        details = "資料庫管理師: 負責資料庫資料以及程式移轉(從 Oracle到IBM DB2), 資料同步,制定規範以及效能調教"
        [[params.experience.list.items]]
        #details = "SA: Identified requirements and designed the application; lead development team to make it real"
        details = "系統分析師: 分析需求, 設計應用系統, 與開發團隊合作實現專案目標"

        [[params.experience.list]]
        title = "程式開發設計師"
        dates = "1998 - 2000"
        company = "宏詹資訊 IISI"
        details = "程式開發"
        [[params.experience.list.items]]
        details = "I took full training of Oracle Database and it’s development tool; Achieved to get certified “Oracle  Certified  Application  Developer  Rel.1”."
        [[params.experience.list.items]]
        #details = "Developed  Shop  floor  control  system  for  Sanyang  Motor  Company  (SYM)  which  is  for  auto  production  line  for  manufacturing."
        details = "Developed Shop floor control system for SYM to build automation control system for car manufacturing"
        [[params.experience.list]]
        title = "STAFF"
        dates = "1996 - 1998"
        company = "長榮國際"
        details = "I were in charge for insurances for aviation including APA, LOL, Aircraft and Liabilities. Coverage included insurance placement, renewal and claim"

       


    [params.projects]
        enable = true

        [[params.projects.list]]
        #title = "CTBC Filenet "
        title = "C Bank Filenet "
        meta = " ITA & SA & SD"
        tagline = "Reverse client's existing spec and code to new design spec and Java code. Incorporate new Filenet solution in the project, tailor new solution to meet requirements and tackle the gap of the new solution. Lead team to develop applications"

        [[params.projects.list]]
        #title = "FCB New Enterprise Bank Portal "
        title = "F Bank New Internet Banking Portal"
        meta = "ITA & SA & SD"
        tagline = "Upgrade and develop new cx portal with new look and feel, multi-lingo capability. Perform HA and Stress test to ensure robustness"

        [[params.projects.list]]
        #title = "Walsin eProcurement"
        title = "W Co. eProcurement"
        meta = "ITA"
        tagline = "Lead team to build eProcurement system(EP) on WAS/Oracle. Interface to SAP via JCO. Design data migration strategy from old system to new EP"

        [[params.projects.list]]
        #title = "TTL Employee Portal"
        title = "T Co. Employee Portal"
        meta = "ITA"
        tagline = "Build up Employee Portal. Integrate client existing authentication  (i.e. AD) to enforce SSO. Integrate client interfaced systems, such as official documents system, e-flow system, contacts system and work time /compensation system.	Plan the interfaces for ERP integration next stage"

        [[params.projects.list]]
        #title = "FCB Enterprise Bank Upgrade"
        title = "F Bank Enterprise Bank Upgrade"
        meta = "ITA"
        tagline = "Upgrade application system, enhance system availability and performance. DB performance tuning including statement tuning and system tuning. Design the architecture to enable HA in the EB(Enterprise Bank) system covering the products of MQ, WAS and DB2. FXML gateway service performance tuning."
        
        [[params.projects.list]]
        #title = "F Center Tax Reform Consulting Project"
        title = "F  Tax Reform Consulting Project"
        meta = "IT Consultant"
        tagline = "Introduce the methodologies to the project to help client blueprint their next system. Methodologies adopted including EA, Guiding Principle, Component Model, Architecture Decision"
        
        [[params.projects.list]]
        #title = "ePost "
        title = "ePost "
        meta = "SA"
        tagline = "SA and SD of the ePost"
      
        [[params.projects.list]]
        #title = "CGH Information"
        title = "C Hospital HIS"
        meta = "DBA"
        tagline = "DB Migration from Oracle to DB2 including data and store procedure.Design multi-districts, data extracts and loading mechanism. Manage schema for SA and perform statement tuning and system performance tuning"
        
        [[params.projects.list]]
        #title = "FCB eCheck"
        title = "F Bank eCheck"
        meta = "ITA & SA"
        tagline = "Integrate client ESB system. Perform TCH MIG/SIG"
        [[params.projects.list]]
        title = "H Bank eCheck"
        #title = "HNCB eCheck"
        meta = "ITA & SA"
        tagline = "Integrate client EAI system.	Perform TCH MIG/SIG"

    [params.information]
        enable = false

        [[params.information.list]]
        title = "Papers"
        [[params.information.list.items]]
        details = "2018 · Lorem Ipsum"
        [[params.information.list.items]]
        details = "2016 · Sed Fringilla"

        [[params.information.list]]
        title = "Interests"
        details = "Climbing, Snowboarding, Photography, Travelling"








    [params.social]
        enable = true

       # [[params.social.list]]
       # icon = "fab fa-github-square"
       # url = "//github.com/username"
       # title = "username"
       # [[params.social.list]]
       # icon = "fab fa-linkedin"
       # url = "//linkedin.com/in/username"
       # title = "username"
       # [[params.social.list]]
       # icon = "fab fa-twitter-square"
       # url = "//twitter.com/username"
       # title = "@username"





